language: node_js
node_js:
  - "10"
notifications:
  email:
    recipients:
      - herezk@gmail.com
      - herez@ime.usp.br
      - herez@herez.com.br
      - xgvieira@gmail.com
      - jgabriel.basi@hotmail.com
      - jairo@jahdsoft.com
    on_success: change
    on_failure: always
